---
title: "Lab05_MC"
author: "Christophoros & Marketos"
date: "11/29/2021"
output: pdf_document
papersize : a4
---

```{r setup, include=FALSE}
library(formatR)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

# Question 1

```{r}
lottery <- read.csv2("lottery.csv")

Y <- lottery$Draft_No
X <- lottery$Day_of_year

set.seed(12345)

bootstrap_X <- matrix(nrow=2000, ncol=length(X))
bootstrap_Y <- matrix(nrow=2000, ncol=length(X))

for (i in 1:2000) {
  bootstrap_X[i,] <- sample(X, replace = TRUE)
  bootstrap_Y[i,] <- Y[bootstrap_X[i,]]
}

T <- list()

for (i in 1:nrow(bootstrap_X)) {
  
  data <- data.frame("DraftNo" = bootstrap_Y[i, ], "DayOfYear" = bootstrap_X[i,])
  
  model <- loess(DraftNo ~ DayOfYear, data=data)
  
  Xb <- bootstrap_X[i,max(which(predict(model, 
                                      bootstrap_X[i,]) == max(predict(model,bootstrap_X[i,]))))]
  Xa <- bootstrap_X[i,min(which(predict(model, 
                                      bootstrap_X[i,]) == min(predict(model,bootstrap_X[i,]))))]
  
  T[i] <- ((predict(model, Xb) - predict(model, Xa)) / (Xb - Xa))
}

data_plot <- data.frame("T" = unlist(T))

library(ggplot2)

my_histogram <- ggplot(data = data_plot, aes(x=T)) +
  geom_histogram(bins = 30,color = "#00798c", fill = "#00798c", aes(y=..density..)) +
  geom_density(colour = "#d1495b") +
  labs(title = "Histogram of T") +
  xlab("Test Statistics") +
  ylab("Density")

my_histogram
```

# Question 2

## Task 1

```{r}
price <- read.csv("prices1.csv", sep = ";")
```

```{r}
library(ggplot2)
my_histogram <- ggplot(price, aes(x=Price)) + 
  geom_histogram(bins = 30,color = "#00798c", fill = "#00798c", aes(y=..density..)) +
  geom_density(colour = "#d1495b") +
  labs(title = "Histogram of the Price variable")
  ylab("Density")

my_histogram
```

```{r}
mean_value <- mean(price$Price)
mean_value
```

## Task 2

The non-parametric bootstrap estimator of bias is given by:

$$
\begin{aligned}
\hat{T} = 2 T(D) - \frac{1}{B} \sum_{i=1}^{B} T(D_{i}^{*})
\end{aligned}
$$

The variance of estimator is given by:

$$
\begin{aligned}
\widehat{Var \left[ T( \cdot ) \right] } &= \frac{1}{B - 1} \sum_{i=1}^{B} (T(D_{i}^{*}) - \overline{T(D^{*})})^2
\end{aligned}
$$

```{r, warning=FALSE}
library("boot")

# statistic 
my_stat_fun <- function(data,indeces){
  return(mean(data[indeces]))
}

# # typical bootstrap replicates 100-2000
# B <- 100
# B <- 200
# B <- 500
B <- 1000
# B <- 1500
# B <- 2000

bootstrap <- boot(data = price$Price, statistic = my_stat_fun, R = B)
mean_estimator <- 2*bootstrap$t0-mean(bootstrap$t)
variance_estimator <- (1/(B-1)) * sum((bootstrap$t-mean(bootstrap$t))^2)
ci <- boot.ci(boot.out = bootstrap,type = c("perc", "bca", "norm")) 
plot(bootstrap) # conf=0.95 default

```

## Task 3

```{r}
normal_low <- ci$normal[,3] - ci$normal[,2]
percent_low <- ci$percent[,5] - ci$percent[,4]
bca_low <- ci$bca[,5] - ci$bca[,4]

normal_upper <- ci$normal[,3] - normal_low/2
percent_upper <- ci$percent[,5] - percent_low/2
bca_upper <- ci$bca[,5] - bca_low/2

intervals <- data.frame( "Normal" = c(normal_low, normal_upper),
                         "Percentile" = c(percent_low, percent_upper),
                         "BCa" = c(bca_low, bca_upper))

rownames(intervals) <- c("Low Interval","Upper Interval")
knitr::kable(intervals)
```

## Task 4

The variance of the mean price using the jackknife is given by $\widehat{Var[T(.)]} = \frac{1}{n(n-1)}\sum_{i=1}^n ((\rm T_i^*)- \rm J(T))^2$, where $T_i^*$ is give by $ T_i^* = nT(D)-(n-1)T(D_i^*)$ and $J(T)$ is given by $J(T)= \frac{1}{n}\sum_{i=1}^{n}T_i^*$.

```{r}
n = nrow(data)

ti <- list()

for(i in 1:n){
  ti[i] <- n * mean(data$Price) - (n-1) * mean(data[-i,1])
}

jt = (1/n) * sum(unlist(ti))

jackknife = (1/(n*(n-1))) * sum((unlist(ti) - jt)^2)
```







